### ISSUE TITLE
Release of teslamate failed

### ISSUE THREAD

**Issue by venc0r** [egeback/helm-charts#28]
Hi,

first of all, thanks for the chart :)
I'm not sure if you have noticed that the release pipeline of the latetest teslamate has failed:

https://github.com/egeback/helm-charts/actions/runs/7864818099/job/21457021981
https://github.com/egeback/helm-charts/actions/runs/7864818100/job/21457022039

With the latest changes of Tesla's API you can't login with the 1.28.2 anymore.

**Comment by egeback** [comment]
Hi

Sorry for that. New release of teslamate https://github.com/egeback/helm-charts/releases/tag/teslamate-1.0.15 and update page release.

Please confirm that can update.

//Marky

**Comment by venc0r** [comment]
My renovate bot picked up the update last night, thx.
